site_name: Kwokon Notebook

theme:
    name: null
    custom_dir: mkdocs_alabaster

nav:
  #- Home: index.md
  Python编程：从入门到实践: Python编程：从入门到实践.md
  零基础入门学习Python: 零基础入门学习Python.md
  - CS 61A：Structure and Interpretation of Computer Programs: CS 61A.md
  - 用Python玩转数据: 用Python玩转数据.md
  - Python核心编程: Python核心编程.md

markdown_extensions:
  - toc:
      permalink: "¶"

extra:
  logo: logo.png
  include_toc: no
